export const publicApiRoutes={
  ownProfile:'/profile/me',
  profileByUserId:'/profile/:id',
  profileImage:'/profile/profile-image',
  search:'/search',
  addSearchHistory:'/search/history/:id',
  removeSearchHistory:'/search/history/:id',
  clearSearchHistory:'/search/history',
  searchHistory:'/search/history',
    getService: "/category/:categoryId/services",
    getCategory:'/category',
    getAvailabilityOfBeautician:'/beautician/:id/schedules',
    getBeauticianServiceList:'/beautician/services/:id',
   getPamplet:'/beautician/pamhlet/:beauticianId',
   changePassword:'/change-password',
   homefeed:'/posts/feed',
   tipsRentFeed:'/posts/tips-rent',
  searchPost:'/posts/search',
   createPost:'/posts',
  getSignedUrl:'posts/upload',
  getMonthlyAvailabilityForCustomer:'/beautician/:id/schedules/month',
  getBeauticianPost:'/beautician/posts/:id',
  //chat
  createChat:'/chats',
  getUserChats:'/chats',
  getChatByparticipants:'/chat/with/:id',
  getMessageByChat:'/chat/:chatId/messages',
  getBookingById:'/bookings/:bookingId',
  createBooking:'/bookings',
  updateBookingStatus:'/bookings/:bookingId/status',
  lockSlot: '/bookings/lock-slot',
  //comment-like
  addLike:'/posts/:postId/like',
  removeLike:'/posts/:postId/like',
  addPostComment:'/posts/:postId/comment',
  getPostComment:'/posts/:postId/comment',
  deleteComment:'/posts/:postId/comment/:commentId',
  //payment
  createOrder:'/bookings/:bookingId/payment',
  verifyPayment:'/payments/verify',
  //refund
  refundRequest:'/bookings/:bookingId/refund-request',
  approverefund:'/bookings/:bookingId/refund-approve',
  disputerefund:'/bookings/:bookingId/refund-dispute',
  //cancel
  cancelBooking:'/bookings/:bookingId/cancel',
  //wallet
  getWallet:'/wallet',
  //notification
  getNotification:'/notifications',
  readAllNotification:'/notifications',
   //replay comment
   getReplyComment:'/posts/:postId/comments/:commentId/replies',
}